apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sregmi2-pipeline
  namespace: argocd
spec:
  destination:
    # Add your campusid below
    namespace: sregmi2-pipeline
    server: "https://kubernetes.default.svc"
  sources:
    - path: k8s/manifests/web
      # Add your github https url below
      repoURL: https://github.com/Motaphe/cicd_pipeline.git
      targetRevision: HEAD
    - path: k8s/manifests/db
      # Add your github https url below with .git extension
      repoURL: https://github.com/Motaphe/cicd_pipeline.git
      targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions: 
    - CreateNamespace=true
    - PruneLast=true
    automated:
      selfHeal: true