apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  # Add your campusid below
  namespace: sregmi2-pipeline
spec:
  storageClassName: sregmi2-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
