apiVersion: v1
kind: Service
metadata:
  name: db
  # Add your campusid below
  namespace: sregmi2-pipeline
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
